---
title: "SCAG Data Task"
author: "Zack Crowley"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# Set R chunk options:
## Set default options for R code chunks:
knitr::opts_chunk$set(
    echo = FALSE, 
    warning = FALSE, 
    message = FALSE 
    # fig.width = 6.5,
    # fig.height = 4
    )
# Prevents sci notation and sets the output of decimals to 4 (0.0000), suppresses warnings/info for tidyverse:
options(scipen = 999,
        tidyverse.quiet = TRUE,
        dplyr.summarise.inform = FALSE)

# Set here() location:
here::i_am("SCAG_data_task_ZC.Rmd")

# Load libraries:
library(here)
library(fs)
library(rstudioapi) 
library(rlang)
library(rstatix)
library(janitor)
library(tidyverse)
library(data.table)
library(tidycensus) # API for US Census- can access ACS PUMS directly from API- key set in .Renviron- to see use: usethis::edit_r_environ()
library(survey)
library(srvyr) # Working with survey data

# # Get data dictionary as tibble from
# pums_vars_acs5 <- pums_variables %>%
#   filter(year == 2021, survey == "acs5")
# # person level
# pums_vars_acs5_person <- pums_variables %>%
#   filter(year == 2021, survey == "acs5", level == "person")
# # housing level:
# pums_vars_acs5_housing <- pums_variables %>%
#    filter(year == 2021, survey == "acs5", level == "housing")
# 
# # Write out data dicts for all vars, person and housing vars:
# write_csv(pums_vars_acs5, "PUMS_docs/pums_vars_acs5.csv")
# write_csv(pums_vars_acs5_person, "PUMS_docs/pums_vars_acs5_person.csv")
# write_csv(pums_vars_acs5_housing, "PUMS_docs/pums_vars_acs5_housing.csv")
# 
# Read in data dicts from person and housign level data:
pums_vars_acs5 <- read_csv("PUMS_docs/pums_vars_acs5.csv")
pums_vars_acs5_person <- read_csv("PUMS_docs/pums_vars_acs5_person.csv")
pums_vars_acs5_housing <- read_csv("PUMS_docs/pums_vars_acs5_housing.csv")
```

### Load in raw ACS data from US Census microdata ACS PUMS data repo:
```{r load in raw ACS data}
# Total list of vars to get from ACS PUMS
vars_list_pums <- c("SERIALNO", "PUMA", "ST", "SPORDER", "RELSHIPP", "PWGTP", "WGTP", "SEX", "AGEP", "HHT", "HISP", 
                    "RAC1P", "ENG", "NATIVITY", "DIS", "SCHL", "ESR", "JWMNP", 
                    "JWTRNS", "TEN","KIT", "PLM", "WAGP", "WKHP", 
                    "ADJINC","VEH","RMSP", "NP", "GRPIP", "OCPIP", "POVPIP")
       
### Housing level data raw:
# Variables to pull out of raw housing data:
housing_vars_list <- c("SERIALNO", "PUMA", "ST","WGTP", "HHT", "TEN", "KIT", "PLM", "ADJINC", "VEH", "RMSP", "NP", "GRPIP", "OCPIP")

# Read in the housing level data, select only vars from housing_vars_list, convert to tibble:
housing_data <- fread("data/csv_hca-Housing_CA/psam_h06.csv", select = housing_vars_list) %>% as_tibble()

### Person level data raw:
# Variables to pull out of raw housing data:
person_vars_list <- c("SERIALNO", "ST", "PUMA", "SPORDER", "RELSHIPP", "PWGTP", "SEX", "AGEP", "HISP", "RAC1P", "ENG", "NATIVITY", "DIS", "SCHL", "ESR", "JWMNP", "JWTRNS", "WAGP", "WKHP", "ADJINC", "POVPIP")
# Set up type list for read_csv:
# person_vars_list_types <- pums_vars_acs5 %>% 
#             distinct(var_code, data_type) %>% 
#             filter(var_code %in% person_vars_list) %>%
#             mutate(var_code =  factor(var_code, levels = person_vars_list)) %>%
#             arrange(var_code) %>% mutate(data_type = case_when(data_type == "chr" ~ "c",
#                                                                data_type == "num" ~ "d")) %>% 
#             tibble::deframe() %>% list()

# Read in the person level data:
person_data <- fread("data/csv_pca-Person_CA/psam_p06.csv", select = person_vars_list) %>% as_tibble()
# person_data <- fread("data/csv_pca-Person_CA/psam_p06.csv", select = person_vars_list, 
#                      colClasses = list(numeric = c("ST", "PUMA", "SPORDER", "RELSHIPP", "PWGTP", "SEX", "AGEP", "HISP", "RAC1P", "ENG", "NATIVITY", 
#                                                    "DIS", "SCHL", "ESR", "JWMNP", "JWTRNS", "WAGP", "WKHP", "ADJINC", "POVPIP"))) %>% as_tibble()

# read_csv
# person_data <- read_csv("data/csv_pca-Person_CA/psam_p06.csv", col_select = person_vars_list, col_types = (list(SERIALNO = "c",
#                                                                                                                 ST       = "d",
#                                                                                                                 PUMA     = "d",
#                                                                                                                 RELSHIPP = "d",
#                                                                                                                 PWGTP    = "d",
#                                                                                                                 SEX      = "d",
#                                                                                                                 AGEP     = "d",
#                                                                                                                 HISP     = "d",
#                                                                                                                 RAC1P    = "d",
#                                                                                                                 ENG      = "c",
#                                                                                                                 NATIVITY = "d",
#                                                                                                                 DIS      = "d",
#                                                                                                                 SCHL     = "c",
#                                                                                                                 ESR      = "c",
#                                                                                                                 JWMNP    = "d",
#                                                                                                                 JWTRNS   = "c",
#                                                                                                                 WAGP     = "d",
#                                                                                                                 WKHP     = "d",
#                                                                                                                 ADJINC   = "c",
#                                                                                                                 POVPIP   = "d")), progress = show_progress()) 



# # Merge the person level data and the housing level data- using the variable `SERIALNO`; left_join on person_data- to only keep data in person-level data:
merged_data <- person_data %>% left_join(., housing_data, by = c("SERIALNO", "ST", "PUMA", "ADJINC"))

# Write out to .csv for the raw data from ACS Data call to folder named "clean_data/acs_data_raw": 1826332 obs. with 31 variables
# write_csv(merged_data, "clean_data/acs_data_raw/merged_acs_data.csv")

# SCAG County list- need to conver PUMA codes to county and then filter whole raw ACS PUMS data set to only these counties:
scag_county_list <- c("Imperial", 
                      "Los Angeles",
                      "Orange",
                      "Riverside",
                      "San Bernardino", 
                      "Ventura")

# Mutate/case_when to replicate SAS code above for creating "county" var- 
# Create couny variable with SCAG counties and filter to only those rows in SCAG Counties using scag_county_list from above:
merged_data_scag <- merged_data %>% mutate(county = case_when(PUMA == 2500 ~ "Imperial", # 25 prefix
                                      PUMA >= 3701 & PUMA <= 3799 ~ "Los Angeles", # 37 prefix
                                      PUMA >= 5901 & PUMA <= 5999 ~ "Orange", # 59 prefix
                                      PUMA >= 6501 & PUMA <= 6599 ~ "Riverside", # 65 prefix
                                      PUMA >= 7101 & PUMA <= 7199 ~ "San Bernardino", # 71 prefix
                                      PUMA >= 11101 & PUMA <= 11199 ~ "Ventura" # 111 prefix
                                                    )) %>% 
                            filter(county %in% scag_county_list) %>% relocate("county", .after = ST) 

# Write out to .csv for the raw data from ACS Data call to folder named "clean_data/acs_data_raw": 879241 obs. (same as API call) with 32 variables
# write_csv(merged_data_scag, "clean_data/acs_data_raw/merged_acs_data_scag.csv")

# # check variables from the merged_data using str() and summary():
# str(merged_data)
```


### CA ACS PUMS Data from 2017-2021- 5 year ACS- Census API Call:
```{r tidycensus CA data}
# List of vars to get from ACS PUMS
vars_list_pums <- c("PUMA","RELSHIPP","SEX", "AGEP", "HHT", "HISP", "RAC1P", "ENG", "NATIVITY", "DIS", "SCHL", "ESR", "JWMNP", "JWTRNS", 
                    "TEN", "KIT", "PLM", "WAGP", "WKHP", "ADJINC","VEH",
                    "RMSP", "NP", "GRPIP", "OCPIP", "POVPIP")


# Return tibble of var_code and var_label for vars_list_pums, arrange by order of vars_list_pums:
pums_data_desc <- pums_vars_acs5 %>% 
            distinct(var_code, var_label, data_type, level) %>% 
            filter(var_code %in% vars_list_pums) %>%
            mutate(var_code =  factor(var_code, levels = vars_list_pums)) %>%
            arrange(var_code)

# List of vars and labels:
#   var_code  var_label                                                                                                                                   data_type   level  
#    <fct>    <chr>                                                                                                                                         <chr>     <chr>  
#  1 PUMA     Public use microdata area code (PUMA) based on 2010 Census definition (areas with population of 100,000 or more, use with ST for unique code) chr       NA     
#  2 RELSHIPP Relationship to reference person                                                                                                              chr       person 
#  3 SEX      Sex                                                                                                                                           chr       person 
#  4 AGEP     Age                                                                                                                                           num       person 
#  5 HHT      Household/family type                                                                                                                         chr       housing
#  6 HISP     Recoded detailed Hispanic origin                                                                                                              chr       person 
#  7 RAC1P    Recoded detailed race code                                                                                                                    chr       person 
#  8 ENG      Ability to speak English                                                                                                                      chr       person 
#  9 NATIVITY Nativity                                                                                                                                      chr       person 
# 10 DIS      Disability recode                                                                                                                             chr       person 
# 11 SCHL     Educational attainment                                                                                                                        chr       person 
# 12 ESR      Employment status recode                                                                                                                      chr       person 
# 13 JWMNP    Travel time to work                                                                                                                           num       person 
# 14 JWTRNS   Means of transportation to work                                                                                                               chr       person 
# 15 TEN      Tenure                                                                                                                                        chr       housing
# 16 KIT      Complete kitchen facilities                                                                                                                   chr       housing
# 17 PLM      Complete plumbing facilities                                                                                                                  chr       housing
# 18 WAGP     Wages or salary income past 12 months (use ADJINC to adjust WAGP to constant dollars)                                                         num       person 
# 19 WKHP     Usual hours worked per week past 12 months                                                                                                    num       person 
# 20 ADJINC   Adjustment factor for income and earnings dollar amounts (6 implied decimal places)                                                           chr       housing
# 21 VEH      Vehicles (1 ton or less) available                                                                                                            chr       housing
# 22 RMSP     Number of rooms                                                                                                                               num       housing
# 23 NP       Number of persons associated with this housing record                                                                                         num       housing
# 24 GRPIP    Gross rent as a percentage of household income past 12 months                                                                                 num       housing
# 25 OCPIP    Selected monthly owner costs as a percentage of household income during the past 12 months                                                    num       housing
# 26 POVPIP   Income-to-poverty ratio recode                                                                                                                num       person 

# Vector of PUMA codes to get from CA- ACS PUMS API Call below:
puma_codes_scag <- c(02500, 03701:03799, 05901:05999, 06501:06599, 07101:07199, 11101:11199)
###
# Run API call to get all California ACS PUMS data from 2017-2021- 5 year ACS: CA FIPS is 06- took about 8 minutes to download API call.
ca_pums <- get_pums(
  variables = vars_list_pums,
  state = "CA", # California
  # puma = c(02500, 03701:03799, 05901:05999, 06501:06599, 07101:07199, 11101:11199),
  survey = "acs5", # acs5 is the 5 year ACS PUMS
  year = 2021, # Gets 2017-2021 ACS PUMS if acs5 set in survey option.
  recode = TRUE, # recode variable values using Census data dictionary and creates a new *_label column for each variable that is recoded.
  show_call  = TRUE # If TRUE, display call made to Census API.
)
# API CALL: Census API call: https://api.census.gov/data/2021/acs/acs5/pums?get=SERIALNO%2CSPORDER%2CWGTP%2CPWGTP%2CPUMA%2CRELSHIPP%2CSEX%2CAGEP%2CHHT%2CHISP%2CRAC1P%2CENG%2CNATIVITY%2CDIS%2CSCHL%2CESR%2CJWMNP%2CJWTRNS%2CTEN%2CKIT%2CPLM%2CWAGP%2CWKHP%2CADJINC%2CVEH%2CRMSP%2CNP%2CGRPIP%2COCPIP%2CPOVPIP&ucgid=0400000US06

# Write out to .csv for the raw data from API call to folder named "clean_data": 1826332 obs. with 49 variables
# write_csv(ca_pums, "clean_data/ca_pums_raw.csv")

### 
#Read in saved API call data:
ca_pums <- read_csv("clean_data/ca_pums_raw.csv")

# Set cols to numeric that ended up as characters, change order of vars:
ca_pums <- ca_pums %>% mutate(across(PUMA:RAC1P, ~ as.numeric(.))) %>% 
    relocate(c("PUMA", "ST", "SPORDER", "SEX", "AGEP","HHT", "HISP","RAC1P", "ENG", "NATIVITY", "DIS", "SCHL","ESR"), .after = SERIALNO)

# Filter data to only PUMAs that we need for SCAG Region: 
# *------ PUMA 2010 -----------------------------------;
# if 		  puma  =2500 then county=25; *Imperial;
# if 3701<= puma <=3799 then county=37; *Los Angeles;
# if 5901<= puma <=5999 then county=59; *Orange;
# if 6501<= puma <=6599 then county=65; *Riverside ;
# if 7101<= puma <=7199 then county=71; *San Bernardino;
# if 11101<= puma <=11199 then county=111; *Ventura;

# SCAG County list- need to conver PUMA codes to county and then filter whole raw ACS PUMS data set to only these counties:
scag_county_list <- c("Imperial", 
                      "Los Angeles",
                      "Orange",
                      "Riverside",
                      "San Bernardino", 
                      "Ventura")
# Mutate/case_when to replicate SAS code above for creating "county" var- 
# Create county variable with SCAG counties and filter to only those rows in SCAG Counties using scag_county_list from above:
ca_pums_scag <- ca_pums %>% mutate(county = case_when(PUMA == 2500 ~ "Imperial", # 25 prefix
                                      PUMA >= 3701 & PUMA <= 3799 ~ "Los Angeles", # 37 prefix
                                      PUMA >= 5901 & PUMA <= 5999 ~ "Orange", # 59 prefix
                                      PUMA >= 6501 & PUMA <= 6599 ~ "Riverside", # 65 prefix
                                      PUMA >= 7101 & PUMA <= 7199 ~ "San Bernardino", # 71 prefix
                                      PUMA >= 11101 & PUMA <= 11199 ~ "Ventura" # 111 prefix
                                                    )) %>% 
                            filter(county %in% scag_county_list) %>% relocate("county", .after = ST) 

# Write out data filtered to only SCAG counties to folder named "clean_data": 879241 obs. with 49 variables
# write_csv(ca_pums_scag, "clean_data/ca_pums_scag.csv")

# # Read in SCAG county data from ca_pums_scag.csv:
# ca_pums_scag <- read_csv("clean_data/ca_pums_scag.csv")
# 
# # Set a list of names of the columns from API call:
# vars_ca_pums_scag <- names(ca_pums_scag)

# Remove all large datasets, leave ca_pums_scag
# rm(merged_data,merged_data_scag,housing_data,person_data,ca_pums)
```

### SCAG Data from ACS PUMS:
```{r read in SCAG data}
# Read in SCAG county data from ca_pums_scag.csv:
ca_pums_scag <- read_csv("clean_data/ca_pums_scag.csv")

# Set a list of names of the columns from API call:
vars_ca_pums_scag <- names(ca_pums_scag)

```


### Recoding variables for use in ACS PUMS Analysis: 
```{r recode}
# Examples of sex by county with weight by person using var "PWGTP"
ca_pums_scag %>% 
  count(county, SEX_label, wt = PWGTP)

ca_pums_scag %>% 
  mutate(ba_above = SCHL %in% c("21", "22", "23", "24")) %>% 
  group_by(county, SEX_label) %>% 
  summarize(
    total_pop = sum(PWGTP),
    mean_age = weighted.mean(AGEP, PWGTP),
    ba_above = sum(PWGTP[ba_above == TRUE & AGEP >= 25]),
    ba_above_pct = ba_above / sum(PWGTP[AGEP >= 25])
  )

```


### Stop

---
